---
- name: Deploy Java WAR file to Tomcat
  hosts: your_tomcat_host
  become: true

  vars:
    tomcat_manager_user: admin
    tomcat_manager_password: password
    war_file_url: http://nexus.example.com/repository/your_war_file.war

  tasks:
    - name: Download WAR file from Nexus
      get_url:
        url: "{{ war_file_url }}"
        dest: /tmp/your_war_file.war

    - name: Remove existing WAR file from Tomcat
      file:
        path: /opt/tomcat/webapps/your_war_file.war
        state: absent
      notify: Restart Tomcat

    - name: Deploy WAR file to Tomcat
      copy:
        src: /tmp/your_war_file.war
        dest: /opt/tomcat/webapps/your_war_file.war
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
