---
- name: Deploy Java WAR file to Tomcat
  hosts: tomcatserver
  become: true

  vars:
    tomcat_manager_user: admin
    tomcat_manager_password: admin
    ##war_file_url: http://54.254.201.4:8081/repository/javaapp/com/example/java-maven/1.0-SNAPSHOT/java-maven-1.0-20230717.104959-2.war
    nexus_repo_url: "http://54.255.174.151:8081/"
    #nexus_username: "your-nexus-username"
    #nexus_password: "your-nexus-password"
    group_id: "com.example"
    artifact_id: "java-maven"
    repository: "javaapp"
    ##tomcat_webapps_path: "/path/to/tomcat/webapps"
    war_filename: "{{ artifact_id }}.war"
  tasks:
    - name: Download WAR file from Nexus
      get_url: 
        url: "{{ nexus_repo_url }}"
        username: admin
        password: password
        group_id: "{{ group_id }}"
        artifact_id: "{{ artifact_id }}"
        version: "1.0-SNAPSHOT"
        repository: "{{ repository }}"
        classifier: "war"
        dest: "/tmp/{{ war_filename }}"

    - name: Remove existing WAR file from Tomcat
      file:
        path: /opt/tomcat/webapps/*.war
        state: absent
      notify: Restart Tomcat

    - name: Deploy WAR file to Tomcat
      copy:
        remote_src: yes
        src: "/tmp/{{ artifact_id }}.war"
        dest: "/path/to/tomcat/webapps/{{ artifact_id }}.war"
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
