---
- hosts: tomcatserver
  vars:
    nexus_repo_url: "http://52.77.234.48:8081"
    nexus_username: "admin"
    nexus_password: "password"
    group_id: "com.example"
    artifact_id: "java-maven"
    version: "1.0-SNAPSHOT"
    repository: "javaapp"
    tomcat_webapps_path: "/opt/tomcat/webapps"
    war_filename: "{{ artifact_id }}.war"
  tasks:
    - name: Get the latest version from Nexus metadata
      uri:
        url: "{{ nexus_repo_url }}/repository/{{ repository }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/maven-metadata.xml"
        return_content: yes
        method: GET
        user: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
      register: metadata_result

    - name: Extract the latest version from Nexus metadata
      set_fact:
        latest_version: "{{ metadata_result.content | from_xml | xml_findall('/metadata/versioning/latest') | first }}"

    - name: Generate download URL for the latest WAR
      set_fact:
        war_download_url: "{{ nexus_repo_url }}/repository/{{ repository }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ latest_version }}.war"

    - name: Download the latest WAR artifact from Nexus
      get_url:
        url: "{{ war_download_url }}"
        dest: "/tmp/{{ war_filename }}"
        force: yes
        headers:
          Authorization: "Basic {{ (nexus_username + ':' + nexus_password) | b64encode }}"
      register: war_download_result

    - name: Check if WAR file was downloaded
      fail:
        msg: "Failed to download the latest WAR file from Nexus"
      when: not war_download_result.changed

    - name: Deploy the WAR file to Tomcat webapps directory
      copy:
        remote_src: yes
        src: "/tmp/{{ war_filename }}"
        dest: "{{ tomcat_webapps_path }}/{{ war_filename }}"
      notify:
        - Restart Tomcat

  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
